# Generated by Django 3.0.8 on 2020-08-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fos', '0008_auto_20200708_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddetails',
            name='discription',
            field=models.CharField(default=1, max_length=1064),
            preserve_default=False,
        ),
    ]
