# Generated by Django 3.0.8 on 2020-08-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fos', '0011_auto_20200810_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooddetails',
            old_name='price',
            new_name='customer_price',
        ),
        migrations.AddField(
            model_name='fooddetails',
            name='dealer_price',
            field=models.CharField(default=1, max_length=1064),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooddetails',
            name='offer_price',
            field=models.CharField(default=1, max_length=1064),
            preserve_default=False,
        ),
    ]
