# Generated by Django 3.0.8 on 2020-09-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fos', '0012_auto_20200810_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_address', models.CharField(max_length=264)),
                ('cust_phone', models.CharField(max_length=14, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Customer Address',
            },
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='cust_device_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='custorderstatus',
            name='cust_review',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryperson',
            name='delivery_person_phone',
            field=models.CharField(max_length=64),
        ),
    ]
